### ISSUE TITLE
Attribute Error in mpi_learn/mpi/process.py

### ISSUE THREAD

**Issue by wghilliard** [vlimant/mpi_learn#11]
python and pip packages used:
```bash
(mpi_test) wghilliard@thecount:~/workdir/mpi_learn$ python --version
Python 2.7.12
(mpi_test) wghilliard@thecount:~/workdir/mpi_learn$ pip freeze
decorator==4.0.11
h5py==2.7.0
Keras==2.0.1
mpi4py==2.0.0
numpy==1.12.1
packaging==16.8
py==1.4.33
pycuda==2016.1.2
pyparsing==2.2.0
pytest==3.0.7
pytools==2016.2.6
PyYAML==3.12
scipy==0.19.0
six==1.10.0
Theano==0.9.0
```

initial command and error
```bash
(mpi_test) wghilliard@thecount:~/workdir/mpi_learn$ mpirun -np 3 ./MPIDriver.py mnist_arch.json train_mnist.list test_mnist.list --loss categorical_crossentropy --epochs 3
--------------------------------------------------------------------------
[[4326,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: thecount

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
Determining number of GPUs...
Determining number of GPUs...
Determining number of GPUs...
Number of GPUs: 10
Process 2 using device gpu1
Number of GPUs: 10
Process 1 using device gpu0
Number of GPUs: 10
Process 0 using device cpu
Using Theano backend.
Using Theano backend.
Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Files for validation:
  mnist_test_0.h5
  mnist_test_1.h5
  mnist_test_2.h5
  mnist_test_3.h5
Creating MPIMaster with rank 0 and parent rank None. (Communicator size 3, Child communicator size 3)
Process 0 compiling model
optimizer: adam
elastic_force: None
loss: categorical_crossentropy
elastic_momentum: 0
elastic_lr: 1.0
validate_every: 600
mode: sgd
worker_optimizer: sgd
sync_every: 1
[thecount:10803] 2 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[thecount:10803] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Using gpu device 1: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5105)
Files for worker 2:
  mnist_train_4.h5
  mnist_train_5.h5
  mnist_train_6.h5
  mnist_train_7.h5
Creating MPIWorker with rank 2 and parent rank 0 on a communicator of size 3
Process 2 compiling model
Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5105)
Files for worker 1:
  mnist_train_0.h5
  mnist_train_1.h5
  mnist_train_2.h5
  mnist_train_3.h5
Creating MPIWorker with rank 1 and parent rank 0 on a communicator of size 3
Process 1 compiling model
Traceback (most recent call last):
  File "./MPIDriver.py", line 125, in <module>
Traceback (most recent call last):
  File "./MPIDriver.py", line 125, in <module>
Traceback (most recent call last):
  File "./MPIDriver.py", line 132, in <module>
    callbacks=callbacks, verbose=args.verbose )
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/manager.py", line 138, in __init__
    histories = manager.process.train() 
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 547, in train
    callbacks=callbacks, verbose=args.verbose )
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/manager.py", line 138, in __init__
    self.make_comms(comm)
    self.init_callbacks(for_worker=self.has_parent)
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 103, in init_callbacks
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/manager.py", line 185, in make_comms
    self.make_comms(comm)
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/manager.py", line 185, in make_comms
    self.callbacks._set_model(self.callback_model)
AttributeError: 'CallbackList' object has no attribute '_set_model'
    verbose=self.verbose, custom_objects=self.custom_objects)
    verbose=self.verbose, custom_objects=self.custom_objects)
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 347, in __init__
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 347, in __init__
    callbacks=callbacks, verbose=verbose, custom_objects=custom_objects )
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 67, in __init__
    callbacks=callbacks, verbose=verbose, custom_objects=custom_objects )
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 67, in __init__
    self.train()
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 355, in train
    self.train()
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 355, in train
    self.init_callbacks(for_worker=True)
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 103, in init_callbacks
    self.init_callbacks(for_worker=True)
  File "/home/wghilliard/workdir/mpi_learn/mpi_learn/mpi/process.py", line 103, in init_callbacks
    self.callbacks._set_model(self.callback_model)
AttributeError: 'CallbackList' object has no attribute '_set_model'
    self.callbacks._set_model(self.callback_model)
AttributeError: 'CallbackList' object has no attribute '_set_model'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[4326,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

change:
```git
(mpi_test) wghilliard@thecount:~/workdir/mpi_learn$ git diff
diff --git a/mpi_learn/mpi/process.py b/mpi_learn/mpi/process.py
index 4ccd7f1..e213e0f 100644
--- a/mpi_learn/mpi/process.py
+++ b/mpi_learn/mpi/process.py
@@ -100,7 +100,7 @@ class MPIProcess(object):
             self.callback_model = self.model.callback_model
         else:
             self.callback_model = self.model
-        self.callbacks._set_model(self.callback_model)
+        self.callbacks.set_model(self.callback_model)
         self.callback_model.stop_training = False
 
     def train(self):

```

**Comment by duanders** [comment]
Thanks.  Fixed by https://github.com/duanders/mpi_learn/commit/a048debed2ca974c9fcacfe30b1739a660ef791d.
